\LoadClass[12pt,cap,c5size,UTF8]{ctexart}
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{PatternRecognition}[2016/10/08 PR class Latex Template written by Cosmo]
\RequirePackage{graphicx, fancyhdr,amsfonts, amsmath, amsopn,amssymb, amstext, amsthm, bm, delarray, ,eqnarray, theorem, multicol, booktabs}

\renewcommand{\title}[1]{
	\center{\heiti \zihao{3} #1}
}

%\titleformat{\subsection}
%{\zihao{4}\heiti\raggedright}
%{}{0em}
%{}
%
%\titleformat{\subsubsection}
%{\zihao{-4}\heiti\raggedright}
%{}{0em}
%{}


